use std::any::Any;

use ndarray::Array2;
use ndarray_rand::RandomExt;
use ndarray_rand::rand_distr::Uniform;

use crate::layer::{Layer, LayerGradients};

#[derive(Debug)]
pub struct DropoutLayer {
    drop_probability: f64,
}

impl Layer for DropoutLayer {
    fn shape(&self) -> (Option<usize>, Option<usize>) {
        (None, None)
    }

    fn forward(&self, input: &Array2<f64>) -> Array2<f64> {
        input.to_owned()
    }

    fn forward_training(&self, input: &Array2<f64>) -> (Array2<f64>, Box<dyn Any>) {
        if self.drop_probability == 0.0 {
            return (input.clone(), Box::new(None::<Array2<f64>>));
        }

        let keep_prob = 1.0 - self.drop_probability;
        let scale = 1.0 / keep_prob;

        // unwrap cannot fail since parameters are static and checked
        let uniform = Uniform::new(0.0, 1.0).unwrap();
        let mask = Array2::random(input.raw_dim(), uniform)
            .mapv(|x| if x < keep_prob { 1.0 } else { 0.0 });

        let output = input * &mask * scale;
        (output, Box::new(Some(mask)))
    }

    fn backward(
        &self,
        grad_output: &Array2<f64>,
        cache: &dyn Any,
    ) -> (Array2<f64>, LayerGradients) {
        // each layer will receive the cache generated by itself
        // therefore dropout layer will receive the mask generated during the forward pass
        let mask_opt = cache.downcast_ref::<Option<Array2<f64>>>().unwrap();
        let grad_input = match mask_opt {
            Some(mask) => grad_output * mask * (1.0 / (1.0 - self.drop_probability)),
            None => grad_output.clone(),
        };
        (grad_input, LayerGradients::empty())
    }

    fn apply_gradients(&mut self, _gradients: &LayerGradients, _learning_rate: f64) {}
}

impl DropoutLayer {
    pub fn new(drop_probability: f64) -> Self {
        if drop_probability < 0.0 || drop_probability >= 1.0 {
            panic!("Dropout probability must be in [0, 1)");
        }
        Self { drop_probability }
    }
}
